char* UIAGSVersionDate = "Tue Dec  9 21:50:23 2014";
char* versionDate = "Tue Dec  9 21:50:23 2014";
char* versionDateStr = "date:=Tue Dec  9 21:50:23 2014";
char* clearcaseView = "/view/igor";
char* clearcaseViewStr = "view:=/view/igor";
char* clearcaseConfigSpec = "\nelement * CHECKEDOUT\nelement * /main/LATEST\n";
char* clearcaseConfigSpecStr = "configSpec:=element * CHECKEDOUTelement * /main/LATEST";
char* compileFlags = "-I/usr/include  -I/usr/include/c++/4.4.7/ -I/usr/include/c++/4.4.7/x86_64-redhat-linux -I/usr/include/c++/4.4.7/backward  -I/usr/local/share -I/usr/local/share/include -B/usr/lib/gcc/x86_64-redhat-linux/4.4.7/ -B/usr/libexec/gcc/x86_64-redhat-linux/4.4.7/  -D__X86 -D__WS6 -Wreturn-type -Wno-write-strings -g -pthread";
char* compileFlagsStr = "g++:=-I/usr/include  -I/usr/include/c++/4.4.7/ -I/usr/include/c++/4.4.7/x86_64-redhat-linux -I/usr/include/c++/4.4.7/backward  -I/usr/local/share -I/usr/local/share/include -B/usr/lib/gcc/x86_64-redhat-linux/4.4.7/ -B/usr/libexec/gcc/x86_64-redhat-linux/4.4.7/  -D__X86 -D__WS6 -Wreturn-type -Wno-write-strings -g -pthread";
char* kernel = "2.6.32-431.23.3.el6.x86_64";
char* kernelstr = "kernel:=2.6.32-431.23.3.el6.x86_64";
char* node = "acnlinc6.pbn.bnl.gov";
char* nodestr = "node:=acnlinc6.pbn.bnl.gov";
char* OSstr = "OS:=Red Hat Enterprise Linux Workstation release 6.5 (Santiago)";
